# Generated by Django 4.1.1 on 2022-10-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nControl', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidoP', models.CharField(max_length=20)),
                ('apellidoM', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('semestre', models.IntegerField()),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
