# Generated by Django 4.1.1 on 2022-11-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
    ]
