# Generated by Django 4.1.1 on 2022-11-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
    ]
